name: Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main" ]

jobs:
  build-plugin-ci:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Setup MAUI
      run: dotnet workload install maui ios android maccatalyst
    - name: Build
      run: dotnet build ./Plugin.Maui.PoppedContentView.sln -c Release
